baseURL = 'https://levevida.blog.br/'
languageCode = 'pt-br'
title = 'Leve Vida - Voe Mais, Pague Menos'
theme = 'levevida-theme'

[params]
  description = 'Aprenda estratégias reais de acúmulo de milhas para viajar mais gastando menos. E-book completo com planilhas e ferramentas práticas.'
  author = 'Emerson - Leve Vida'
  
  # Informações de contato ATUALIZADAS
  email = 'equipelevevida@gmail.com'
  whatsapp = '5565993317054'
  
  # Redes sociais CORRETAS
  [params.social]
    instagram = 'https://instagram.com/levevida8'
    youtube = 'https://youtube.com/@levevida8'
    tiktok = 'https://tiktok.com/@levevida88'
    kwai = 'https://kwai.com/@levevida88'
  
  # Google Analytics (configure seu ID)
  googleAnalytics = 'G-XXXXXXXXXX'
  
  # SEO
  [params.seo]
    keywords = 'milhas aéreas, pontos de cartão, viagem barata, passagens aéreas, acúmulo de milhas, programas de fidelidade'

# Menu Principal
[menu]
  [[menu.main]]
    name = 'Início'
    url = '/'
    weight = 1
  
  [[menu.main]]
    name = 'Guias'
    url = '/guias/'
    weight = 2
  
  [[menu.main]]
    name = 'Artigos'
    url = '/artigos/'
    weight = 3
  
  [[menu.main]]
    name = 'E-books'
    url = '/ebooks/'
    weight = 4
  
  [[menu.main]]
    name = 'Sobre'
    url = '/sobre/'
    weight = 5
  
  [[menu.main]]
    name = 'Contato'
    url = '/contato/'
    weight = 6

# Configurações de conteúdo
[taxonomies]
  tag = 'tags'
  categoria = 'categorias'

# Output formats
[outputs]
  home = ['HTML', 'RSS', 'JSON']
  section = ['HTML', 'RSS']

# Permalinks
[permalinks]
  artigos = '/artigos/:slug/'
  guias = '/guias/:slug/'
  ebooks = '/ebooks/:slug/'

# Markup
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'monokai'
    lineNos = false

# Privacy
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
  [privacy.youtube]
    privacyEnhanced = true
